import React, { PropsWithChildren, ReactNode, useReducer } from 'react';
import { LaptopOutlined, NotificationOutlined, UserOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Breadcrumb, Layout as Antdlayout, Menu, theme } from 'antd';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { DownOutlined } from '@ant-design/icons';
import { Dropdown, Space } from 'antd';
import Head from 'next/head'

import styles from './index.module.css';

const { Header, Content, Sider } = Antdlayout;

const items = [
    {
        key: " goods",
        // icon: React.createElement(icon),
        label: "商品管理",

        children: [
            { label: "商品列表", key: "/goods" },
            { label: "商品添加", key: "/goods/add" },
        ],
    },

]

const user_items: MenuProps['items'] = [
    {
        label: '用户中心',
        key: '0',
    },
    {
        label: '登出',
        key: '1',
    },
];



export const Layout: React.FC<PropsWithChildren> = ({ children }) => {
    const {
        token: { colorBgContainer },
    } = theme.useToken();

    const router = useRouter();

    // const handlemenuclick=({key})=>{
    //     router.push(key);
    // }
    const handlemenuclick: MenuProps["onClick"] = ({ key }) => {
        router.push(key);
    }



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Antdlayout>
                    <Header className={styles.header}>
                        <Image src='/financeLogo.png' width={40} height={40} className={styles.financeLogo} alt='' />
                        携程购物管理平台
                        {/* 用户下拉菜单 */}
                        <span className={styles.user}>
                            <Dropdown menu={{ items: user_items }}>
                                <a onClick={(e) => e.preventDefault()}>
                                    用户名
                                    {'\u00A0'}
                                    <DownOutlined />
                                </a>
                            </Dropdown>
                        </span>
                    </Header>
                    <Antdlayout className={styles.sectionInner}>
                        <Sider width={200} >
                            <Menu
                                mode="inline"
                                defaultSelectedKeys={["/goods"]}
                                defaultOpenKeys={["goods"]}
                                style={{ height: '100%', borderRight: 0 }}
                                items={items}
                                onClick={handlemenuclick}
                            />
                        </Sider>
                        <Antdlayout className={styles.sectioncontent}>
                            <Content className={styles.content}>
                                {children}
                            </Content>
                        </Antdlayout>
                    </Antdlayout>
                </Antdlayout>
            </main>
        </>
    )

}